services:
  database:
    image: postgres:17.2
    container_name: weekme_database
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
